apiVersion: v1
kind: Service
metadata:
  name: week9app-service
spec:
  type: NodePort
  selector:
    app: week9app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080

